### ISSUE TITLE
Onboarding link does not work

### ISSUE THREAD

**Issue by ThomasKomenda** [deltaDAO/mvg-portal#161] opened 2022-07-14 10:34 UTC
## Summary
in our new tab "ecosystem", the onboarding tutoral link issues a 503 error

## Current Behavior
503 error
  
## Expected Behavior
onboarding tutorial appers

## Steps to Reproduce

1. open mvg portal
2. select tab Ecosystem
3. select onboarding tutorial
4. see error 503
![image](https://user-images.githubusercontent.com/99354530/178963315-cb944e5e-4b80-49fd-a568-16a0019975e0.png)
![image](https://user-images.githubusercontent.com/99354530/178963357-d28628d2-8385-47a7-aa7d-569ad07370f0.png)

**Comment by LucaMilanese90** [comment] 2022-07-14 10:46
The link is working as expected, the problem is that the onboarding service is not available at the moment, nothing we can do from the portal except remove the link until the service is back up again.

**Comment by ThomasKomenda** [comment] 2022-07-14 10:49
okay then I close the issue for now

**Comment by LucaMilanese90** [comment] 2022-07-14 10:50
I would leave it open until we decide if we want to remove the link from the menu or not

**Comment by moritzkirstein** [comment] 2022-07-14 11:13
I think we should remove the link for now, as this will not be resolved in the near future.

**Closed** 2022-07-14 13:42 UTC
Labels: Type: Bug
